modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="gooeylibs2"
version="${version}"
displayName="GooeyLibs2"
authors="landonjw"
description='''
Server-side library that allows for easy user interface development.
'''

[[dependencies.gooeylibs2]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="SERVER"

[[dependencies.gooeylibs2]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1]"
   ordering="NONE"
   side="SERVER"
